// PARA COLOCAR UM LABEL EM CIMA DO OUTRO BASTA CLICA DEFINIR LAYOUT E SELECIONAR LAUYOUT ABSOLUTO
package classes;

import java.awt.Font;


public class TelaGenio extends javax.swing.JFrame {

    public TelaGenio() { //CONSTRUTOR
        initComponents();
        lblN1.setText("<html>VOU PENSA EM UM VALOR ENTRE 1 E 5. TENTE ADVINHAR<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinnerN2 = new javax.swing.JSpinner();
        btnN3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/images.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, 200));

        lblN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/images (2).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 230, 220));

        jLabel2.setText("VALOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, -1));

        spinnerN2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spinnerN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 292, 50, 30));

        btnN3.setText("PALPITE");
        btnN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN3ActionPerformed
        
        // declaração de variavel
        double aleatorio;
        int aleatoriointeiro, usuario;
        String x1,x2,resultado;
        
        
        // vai gerar um vlao aleatório entre 1 e 5
        aleatorio = Math.random();
        aleatoriointeiro = (int) (1 + aleatorio *(6 - 1));
        
        // pega o valor do objeto spinner
        usuario = Integer.parseInt(spinnerN2.getValue().toString());
        
        x1 = "ACERTOU";
        x2 = "<html>ERROU! EU PENSEI NO VALOR  "+ aleatoriointeiro + "<html>";
        
        // OPERADOR TERNARIO
        resultado = (aleatoriointeiro == usuario) ? x1:x2;
        
        // ALTERA O TAMANHO DA FONTE
        lblN1.setFont(new Font("ARIAL BLACK",Font.PLAIN,16));
        
        lblN1.setText(resultado);
        
       
        
        
        
        
        
       
        
        
    }//GEN-LAST:event_btnN3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnN3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblN1;
    private javax.swing.JSpinner spinnerN2;
    // End of variables declaration//GEN-END:variables
}
