/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tipodetriangulo;

/**
 *
 * @author danie
 */
public class TipoTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TipoTriangulo
     */
    public TipoTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sliderX1 = new javax.swing.JSlider();
        sliderX2 = new javax.swing.JSlider();
        sliderX3 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        valorX1 = new javax.swing.JLabel();
        valorX2 = new javax.swing.JLabel();
        valorX3 = new javax.swing.JLabel();
        resF1 = new javax.swing.JLabel();
        resF2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("SEGMENTO A :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 14, 83, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("SEGMENTO B:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 39, 83, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("SEGMENTO C:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 65, 83, -1));

        sliderX1.setForeground(new java.awt.Color(51, 0, 255));
        sliderX1.setMaximum(20);
        sliderX1.setValue(0);
        sliderX1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderX1StateChanged(evt);
            }
        });
        getContentPane().add(sliderX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 13, -1, -1));

        sliderX2.setForeground(new java.awt.Color(51, 0, 255));
        sliderX2.setMaximum(20);
        sliderX2.setValue(0);
        sliderX2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderX2StateChanged(evt);
            }
        });
        getContentPane().add(sliderX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 35, -1, -1));

        sliderX3.setForeground(new java.awt.Color(51, 51, 255));
        sliderX3.setMaximum(20);
        sliderX3.setValue(0);
        sliderX3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderX3StateChanged(evt);
            }
        });
        getContentPane().add(sliderX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 61, -1, -1));

        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("VERIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 99, -1, -1));

        valorX1.setForeground(new java.awt.Color(0, 102, 102));
        valorX1.setText("0");
        getContentPane().add(valorX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 14, 37, -1));

        valorX2.setForeground(new java.awt.Color(0, 102, 102));
        valorX2.setText("0");
        getContentPane().add(valorX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 36, 37, -1));

        valorX3.setForeground(new java.awt.Color(0, 102, 102));
        valorX3.setText("0");
        getContentPane().add(valorX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 62, 37, -1));

        resF1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resF1.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(resF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 160, 226, 16));

        resF2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        resF2.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(resF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 206, 160, 19));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pexels-katerina-holmes-5905613.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderX1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderX1StateChanged
        valorX1.setText(Integer.toString(sliderX1.getValue()));
    }//GEN-LAST:event_sliderX1StateChanged

    private void sliderX2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderX2StateChanged
        valorX2.setText(Integer.toString(sliderX2.getValue()));
    }//GEN-LAST:event_sliderX2StateChanged

    private void sliderX3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderX3StateChanged
       valorX3.setText(Integer.toString(sliderX3.getValue()));
    }//GEN-LAST:event_sliderX3StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a,b,c,maior;
        
       
        // pegando os valores passado pelo slider e amazenando nas variaveis
        a = sliderX1.getValue();
        b = sliderX2.getValue();
        c = sliderX3.getValue();
       
        // verificando o lado maior
        maior = a;
        
        if( b > a && b > c){
            maior = b;
        }
        else if(c > a && c > b){
            maior = c;
        }
       // verificando de forma um triângulo
       if ((a + b + c - maior) > maior){
            resF1.setText("FORMA UM TRIÂNGULO");
            
            if(a == b  && b == c ){
                resF2.setText("EQUILÁTERO");
            }
            
            else if((a != b) && (a != c) && (c != b)){
                resF2.setText("ESCALENO");
            }
            else{
                resF2.setText("ISÓSCELES");
            
            }
            
       }
       else{
           resF1.setText("NÃO FORMA UM TRIÂNGULO");
           resF2.setText("-----------");
       
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel resF1;
    private javax.swing.JLabel resF2;
    private javax.swing.JSlider sliderX1;
    private javax.swing.JSlider sliderX2;
    private javax.swing.JSlider sliderX3;
    private javax.swing.JLabel valorX1;
    private javax.swing.JLabel valorX2;
    private javax.swing.JLabel valorX3;
    // End of variables declaration//GEN-END:variables
}
